version: '3.8'
services:
  redis:
    build: 
      context: .
      dockerfile: Dockerfile_redis
    restart: always
    ports:
      - "6379:6379"
    container_name: redis
   
  
  bot:
    build: 
      context: .
    restart: always
    env_file:
      - stack.env
    container_name: finance_level_bot