version: '3.8'
services:
  redis:
    image: redis:latest
    restart: always
    #command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    ports:
      - "6379:6379"
    container_name: redis
    env_file:
      - .stack
#    networks:
#      - main-net
  
  bot:
    build: 
      context: .
    restart: always
    env_file:
      - .stack
    container_name: finance_level_bot
    #    networks:
    #      - main-net

#networks:
#  main-net:
#    driver: bridge