version: '3.8'
services:
  redis:
    image: redis:latest
    restart: always
    #command: --save 60 1 --loglevel nothing
    ports: 
      - "6379:6379"
    container_name: redis

#  redis:
#    build: 
#      context: .
#      dockerfile: Dockerfile_redis
#      privileged: true
#    restart: always
#    ports:
#      - "6379:6379"
#    container_name: redis
   
  
  bot:
    build: 
      context: .
    restart: always
    env_file:
      - stack.env
    container_name: finance_level_bot